#!/usr/bin/env python3
"""Create a compact, reproducible audit of the pinned model metadata."""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "models"
NAMES = ("radixark", "unsloth", "qwen_base")
HASH_FILES = (
    "tokenizer.json",
    "tokenizer_config.json",
    "chat_template.jinja",
    "generation_config.json",
)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def quantizer_summary(config: dict) -> dict:
    quant = config.get("quantization_config") or {}
    groups = {}
    for name, group in quant.get("config_groups", {}).items():
        groups[name] = {
            "target_count": len(group.get("targets", [])),
            "targets": group.get("targets", []),
            "weights": group.get("weights"),
            "input_activations": group.get("input_activations"),
        }
    ignore = quant.get("ignore", [])
    return {
        "quant_method": quant.get("quant_method"),
        "format": quant.get("format"),
        "quant_algo": quant.get("quant_algo"),
        "global_compression_ratio": quant.get("global_compression_ratio"),
        "kv_cache_scheme": quant.get("kv_cache_scheme"),
        "groups": groups,
        "ignore_count": len(ignore),
        "ignore": ignore,
        "producer": quant.get("producer"),
        "version": quant.get("version"),
    }


def audit_model(name: str) -> dict:
    folder = MODELS / name
    config = read_json(folder / "config.json")
    text = config.get("text_config", config)
    index = read_json(folder / "model.safetensors.index.json")
    weight_map = index["weight_map"]
    files = Counter(weight_map.values())
    result = {
        "architecture": config.get("architectures"),
        "model_type": config.get("model_type"),
        "dtype": text.get("dtype"),
        "native_context": text.get("max_position_embeddings"),
        "rope_parameters": text.get("rope_parameters"),
        "geometry": {
            "layers": text.get("num_hidden_layers"),
            "linear_attention_layers": text.get("layer_types", []).count(
                "linear_attention"
            ),
            "full_attention_layers": text.get("layer_types", []).count(
                "full_attention"
            ),
            "hidden_size": text.get("hidden_size"),
            "intermediate_size": text.get("intermediate_size"),
            "attention_heads": text.get("num_attention_heads"),
            "kv_heads": text.get("num_key_value_heads"),
            "attention_head_dim": text.get("head_dim"),
            "linear_qk_heads": text.get("linear_num_key_heads"),
            "linear_value_heads": text.get("linear_num_value_heads"),
            "linear_head_dim": text.get("linear_value_head_dim"),
            "vocab_size": text.get("vocab_size"),
        },
        "mtp": {
            "configured_layers": text.get("mtp_num_hidden_layers"),
            "indexed_tensor_count": sum("mtp" in key for key in weight_map),
            "indexed_tensors": [key for key in weight_map if "mtp" in key],
        },
        "quantization": quantizer_summary(config),
        "weights": {
            "metadata": index.get("metadata"),
            "indexed_tensor_count": len(weight_map),
            "files": dict(sorted(files.items())),
            "lm_head_tensors": [key for key in weight_map if key.startswith("lm_head")],
        },
        "file_hashes": {
            filename: {
                "bytes": (folder / filename).stat().st_size,
                "sha256": sha256(folder / filename),
            }
            for filename in HASH_FILES
        },
        "generation_config": read_json(folder / "generation_config.json"),
    }
    return result


def comparison_markdown(audit: dict, repos: dict) -> str:
    r = audit["radixark"]
    u = audit["unsloth"]
    rr = repos["radixark"]
    ur = repos["unsloth"]
    same_tokenizer = all(
        r["file_hashes"][item]["sha256"] == u["file_hashes"][item]["sha256"]
        for item in HASH_FILES
    )
    rgroups = r["quantization"]["groups"]
    ugroups = u["quantization"]["groups"]
    return f"""# Model metadata comparison

Generated by `scripts/audit_models.py` from pinned repository metadata. It does
not infer runtime kernel selection; startup logs are the authority for that.

| Property | RadixArk | Unsloth |
|---|---|---|
| Repository revision | `{rr['resolved_revision']}` | `{ur['resolved_revision']}` |
| Repository storage | {rr['total_file_bytes']:,} bytes | {ur['total_file_bytes']:,} bytes |
| Quantization producer/method | ModelOpt / `{r['quantization']['quant_method']}` | Unsloth Dynamic V3 preview / `{u['quantization']['quant_method']}` |
| Quantization format | mixed FP8 + NVFP4 | `{u['quantization']['format']}` mixed precision |
| Main FP8 group | {rgroups['group_0']['target_count']} explicit targets, static W8A8 | {ugroups['group_0']['target_count']} regex targets, W8 plus dynamic A8 |
| NVFP4 group | {rgroups['group_1']['target_count']} explicit targets, static W4A4 group 16 | {ugroups['group_1']['target_count']} regex target, W4 plus local-dynamic A4 group 16 |
| `lm_head` | NVFP4 W4A4; 4 indexed tensors | FP8 W8A8; 2 indexed tensors |
| MTP | {r['mtp']['configured_layers']} layer; {r['mtp']['indexed_tensor_count']} indexed tensors; excluded from quantization | {u['mtp']['configured_layers']} layer; {u['mtp']['indexed_tensor_count']} indexed tensors; separate shard; excluded from quantization |
| KV-cache metadata | static FP8 | static tensorwise symmetric FP8 with observer metadata |
| Indexed weight bytes | {r['weights']['metadata']['total_size']:,} | {u['weights']['metadata']['total_size']:,} |
| Indexed tensors | {r['weights']['indexed_tensor_count']:,} | {u['weights']['indexed_tensor_count']:,} |
| Tokenizer/template files identical | {same_tokenizer} | {same_tokenizer} |

Both checkpoints declare the same 64-layer Qwen3.8 architecture: 48 linear
attention layers and 16 full-attention layers, a native 262,144-token context,
and one MTP layer. Their tokenizer and chat-template hashes differ, so each run
uses the files shipped with its checkpoint.

## Important compatibility qualification

The Unsloth model card explicitly says this checkpoint does **not** work with
released SGLang because its FP8-quantized `lm_head` was not dispatched to a
compressed-tensors linear scheme. The Unsloth rows in this experiment therefore
use a narrow local backport of upstream SGLang PR #34904 on top of the unmerged
Qwen3.8 support branch. They are experimental patched-runtime results, not
claims of support by an official SGLang release.

The RadixArk checkpoint is not uniformly W4A4. Its MLP projections and
`lm_head` are NVFP4 W4A4, while attention projections are FP8 W8A8; MTP and
vision tensors remain unquantized. Unsloth also uses a mixed scheme, with its
last eight layers' MLP projections and its `lm_head` kept at FP8.

See `model_audit.json` for exact targets, ignored modules, tensor names, hashes,
and generation settings.
"""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Regenerate the tracked audit from pinned local model metadata."
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Confirm replacement of the tracked audit and comparison files.",
    )
    args = parser.parse_args(argv)
    if not args.write:
        parser.error("refusing to replace tracked audit files without --write")
    return args


def main(argv: list[str] | None = None) -> int:
    parse_args(argv)
    audit = {name: audit_model(name) for name in NAMES}
    (MODELS / "model_audit.json").write_text(
        json.dumps(audit, indent=2, sort_keys=True) + "\n"
    )
    repos = read_json(MODELS / "repositories.json")
    (MODELS / "model_comparison.md").write_text(comparison_markdown(audit, repos))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
